package uz.pdp.apptelegrammanagergroupbot.enums;

public enum StateEnum {
    START,
    OWNER_SENDING_PHOTO,
    CHOOSE_PERMISSION,
    PERMISSION_EXPIRE, USE_CODE,  CHOOSES_PAYMENT, ADMIN_SENDING_CONTACT, ADMIN_SENDING_TOKEN, ADMIN_SENDING_BOT_USERNAME,
}
